name: Build Jar

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          openssl aes-256-cbc -d -in keystore.jks.encrypted -out keystore.jks -k ${{ secrets.ENCRYPTION_KEY }} -A -pbkdf2
          export KEY_STORE="${{ secrets.KEY_STORE }}"
          ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: GregPatcher
          path: build/libs/*1.12.2*